### ISSUE TITLE
NPE on log file rotation

### ISSUE THREAD

**Issue by kc7bfi** [vy/rotating-fos#26] opened 2021-06-29 17:48 UTC
I am seeing the following errors in my log. Any idea what could be causing them?

```
2021-06-28 19:00:04.766 ERROR [com.vlkan.rfos.LoggingRotationCallback] (RotationJanitor-26:) rotation failure {policy=DailyRotationPolicy, instant=2021-06-29T00:00:00Z, file=null}: java.lang.RuntimeException: rotation failure {instant=2021-06-29T00:00:00Z}
        at com.vlkan.rfos.RotatingFileOutputStream.rotate(RotatingFileOutputStream.java:79)
        at com.vlkan.rfos.policy.TimeBasedRotationPolicy.lambda$createTask$0(TimeBasedRotationPolicy.java:54)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
```

**Comment by vy** [comment] 2021-07-01 18:54
@kc7bfi, thanks for reporting the issue. At first sight, I could not spot the reason. The context of the NPE is missing. Would it be possible for you to reproduce this in a unit test or something similar?

**Comment by kc7bfi** [comment] 2021-07-01 19:01
I can try. It would be nice if the message included the location of the NPE (the stack trace of the NPE itself, not just where it was caught). I will see if I can reproduce the error.

**Comment by vy** [comment] 2021-07-01 19:11
The caught exception is rethrown as follows:

```java
try {
    unsafeRotate(policy, instant);
} catch (Exception error) {
    String message = String.format("rotation failure {instant=%s}", instant);
    RuntimeException extendedError = new RuntimeException(message, error);
    config.getCallback().onFailure(policy, instant, null, extendedError);
}
```

I am clueless on how come the stack trace of the NPE is missing.

**Comment by kc7bfi** [comment] 2021-07-01 19:19
I have seen log4j suppress a stack trace if it happens too often. I will continue to monitor and let you know if the issue resurfaces. TNX

**Comment by kc7bfi** [comment] 2021-07-02 13:20
I found a stack trace that included the NPE:

2021-07-01 19:00:00.643 ERROR [com.vlkan.rfos.LoggingRotationCallback] (RotationJanitor-27:) rotation failure {policy=DailyRotationPolicy, instant=2021-07-02T00:00:00Z, file=null}: java.lang.RuntimeException: rotation failure {instant=2021-07-02T00:00:00Z}
        at com.vlkan.rfos.RotatingFileOutputStream.rotate(RotatingFileOutputStream.java:79)
        at com.vlkan.rfos.policy.TimeBasedRotationPolicy.lambda$createTask$0(TimeBasedRotationPolicy.java:54)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at com.vlkan.rfos.RotatingFileOutputStream.unsafeRotate(RotatingFileOutputStream.java:101)
        at com.vlkan.rfos.RotatingFileOutputStream.rotate(RotatingFileOutputStream.java:76)


Hope this helps.

**Comment by vy** [comment] 2021-07-05 07:32
@kc7bfi, thanks for the stack trace! I will look into this. Which version are you using?

**Comment by kc7bfi** [comment] 2021-07-10 12:42
Sorry for the delay in responding, I was on vacation. I am using version 0.9.2.

**Comment by vy** [comment] 2021-07-23 13:01
I think what is happening is that the `RotatingFileOutputStream` is `close()`d, yet one of the (time-based?) policies are still trying to rotate it. I will try to address this in #14. I will see if I can reproduce this in a test first.

**Comment by vy** [comment] 2021-07-23 14:33
Indeed the issue arises when any `RotatingFileOutputStream` method is accessed when the stream is already closed. In your case, the stream is closed, yet the time-based rotation policy running in the background thread is still trying to rotate it. The problem is actually deeper: closing an RFOS does not stop the scheduled tasks. See my remarks regarding `RotationContext` in #14.

**Comment by kc7bfi** [comment] 2021-07-26 13:16
Thanks for the follow-up. Is it something that you will be able to fix in the next release? ANy idea when that might be?

**Comment by vy** [comment] 2021-07-26 17:36
@kc7bfi, I have just pushed a fix to `master`. Would you mind confirming if `0.9.3-SNAPSHOT` fixes the issue for you, please? (You need to build & install it yourself, snapshot versions are not available in Maven Central.)

**Comment by kc7bfi** [comment] 2021-07-26 18:05
Yes. However, it may be a few days before I can confirm. Thanks for your quick support.

**Comment by kc7bfi** [comment] 2021-07-26 18:10
The tests fail, is that to be expected?

[ERROR] Failures:
[ERROR]   RotatingFileOutputStreamTest.test_write_insensitive_policy:59->test_write_insensitive_policy:173
No interactions wanted here:
-> at com.vlkan.rfos.RotatingFileOutputStreamTest.test_write_insensitive_policy(RotatingFileOutputStreamTest.java:173)
But found this interaction on mock 'rotationPolicy':
-> at java.lang.Iterable.forEach(Iterable.java:75)
***
For your reference, here is the list of all invocations ([?] - means unverified).
1. -> at com.vlkan.rfos.RotatingFileOutputStream.collectWriteSensitivePolicies(RotatingFileOutputStream.java:52)
2. -> at com.vlkan.rfos.RotatingFileOutputStream.startPolicies(RotatingFileOutputStream.java:61)
3. [?]-> at java.lang.Iterable.forEach(Iterable.java:75)

[ERROR]   RotatingFileOutputStreamTest.test_write_insensitive_policy_with_compression:64->test_write_insensitive_policy:173
No interactions wanted here:
-> at com.vlkan.rfos.RotatingFileOutputStreamTest.test_write_insensitive_policy(RotatingFileOutputStreamTest.java:173)
But found this interaction on mock 'rotationPolicy':
-> at java.lang.Iterable.forEach(Iterable.java:75)
***
For your reference, here is the list of all invocations ([?] - means unverified).
1. -> at com.vlkan.rfos.RotatingFileOutputStream.collectWriteSensitivePolicies(RotatingFileOutputStream.java:52)
2. -> at com.vlkan.rfos.RotatingFileOutputStream.startPolicies(RotatingFileOutputStream.java:61)
3. [?]-> at java.lang.Iterable.forEach(Iterable.java:75)

[ERROR] Errors:
[ERROR]   RotatingFileOutputStreamTest.test_empty_files_are_not_rotated » IO Failed to d...
[ERROR]   RotatingFileOutputStreamTest.test_write_sensitive_policy » IO Failed to delete...

**Comment by vy** [comment] 2021-07-26 18:12
Maybe one shouldn't code at night... @kc7bfi, I will check it right away.

**Comment by vy** [comment] 2021-07-26 20:42
@kc7bfi, should be working now. Mind trying again, please?

**Comment by kc7bfi** [comment] 2021-07-26 20:55
That compiled. I'll try to give it a test tomorrow. TNX

**Comment by kc7bfi** [comment] 2021-07-29 15:17
I have not seen this condition reoccurring with the new code. Good work!

**Comment by vy** [comment] 2021-07-30 10:02
@kc7bfi, I will improve the docs a bit more and publish a new release within a day or two. (Will let you know.) Thanks so much again for the report!

**Comment by vy** [comment] 2021-07-31 18:52
`0.9.3` should appear in Maven Central momentarily with this fix included.

**Closed by vy** 2021-07-31 18:52 UTC
